### ISSUE TITLE
Analysis Window vs. Plotting Window sliders: do we really want both?

### ISSUE THREAD

**Issue by kachergis** [langcog/peekbank-shiny#5]
seems a little redundant to me (or at a minimum, you wouldn't want the values of these two to be non-overlapping?) -- anybody else want to weigh in on this? is it as we want?

**Comment by kachergis** [comment]
at a minimum, it seems like you would want plotting window to always be larger than analysis window

**Comment by mcfrank** [comment]
added documentation but left these because they have different functions.
